#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RestaurantsXamarin.Resource", IsApplication=true)]

namespace RestaurantsXamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int avatar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int EatinatorButton = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int restaurantHome = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070033
			public const int account = 2131165235;
			
			// aapt resource value: 0x7f070032
			public const int add = 2131165234;
			
			// aapt resource value: 0x7f070010
			public const int addRestaurant = 2131165200;
			
			// aapt resource value: 0x7f07001b
			public const int address = 2131165211;
			
			// aapt resource value: 0x7f070030
			public const int cancel = 2131165232;
			
			// aapt resource value: 0x7f07002f
			public const int delete = 2131165231;
			
			// aapt resource value: 0x7f07001e
			public const int description = 2131165214;
			
			// aapt resource value: 0x7f070017
			public const int eatinator = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int email = 2131165210;
			
			// aapt resource value: 0x7f070031
			public const int errorsEdit = 2131165233;
			
			// aapt resource value: 0x7f070035
			public const int exit = 2131165237;
			
			// aapt resource value: 0x7f070020
			public const int favouriteFoods = 2131165216;
			
			// aapt resource value: 0x7f070022
			public const int favouritePlace = 2131165218;
			
			// aapt resource value: 0x7f070018
			public const int firstName = 2131165208;
			
			// aapt resource value: 0x7f07002c
			public const int firstNameEdit = 2131165228;
			
			// aapt resource value: 0x7f070027
			public const int image = 2131165223;
			
			// aapt resource value: 0x7f070029
			public const int imageView1 = 2131165225;
			
			// aapt resource value: 0x7f070019
			public const int lastName = 2131165209;
			
			// aapt resource value: 0x7f07002d
			public const int lastNameEdit = 2131165229;
			
			// aapt resource value: 0x7f070015
			public const int linearLayout1 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int linearLayout2 = 2131165206;
			
			// aapt resource value: 0x7f070013
			public const int login = 2131165203;
			
			// aapt resource value: 0x7f070025
			public const int name = 2131165221;
			
			// aapt resource value: 0x7f070012
			public const int password = 2131165202;
			
			// aapt resource value: 0x7f07002b
			public const int passwordEdit = 2131165227;
			
			// aapt resource value: 0x7f07001c
			public const int phone = 2131165212;
			
			// aapt resource value: 0x7f070023
			public const int profileImageUrl = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int register = 2131165220;
			
			// aapt resource value: 0x7f07000b
			public const int restaurantAddress = 2131165195;
			
			// aapt resource value: 0x7f070005
			public const int restaurantDescription = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int restaurantEmail = 2131165193;
			
			// aapt resource value: 0x7f07000f
			public const int restaurantImageUrl = 2131165199;
			
			// aapt resource value: 0x7f070001
			public const int restaurantName = 2131165185;
			
			// aapt resource value: 0x7f07000d
			public const int restaurantPhone = 2131165197;
			
			// aapt resource value: 0x7f070003
			public const int restaurantType = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int restaurantWorkingTime = 2131165191;
			
			// aapt resource value: 0x7f070034
			public const int restaurants = 2131165236;
			
			// aapt resource value: 0x7f070014
			public const int result = 2131165204;
			
			// aapt resource value: 0x7f07002e
			public const int save = 2131165230;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070021
			public const int textView10 = 2131165217;
			
			// aapt resource value: 0x7f07000e
			public const int textView11 = 2131165198;
			
			// aapt resource value: 0x7f070002
			public const int textView2 = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int textView3 = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int textView4 = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int textView5 = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int textView6 = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int textView7 = 2131165196;
			
			// aapt resource value: 0x7f07001d
			public const int textView8 = 2131165213;
			
			// aapt resource value: 0x7f07001f
			public const int textView9 = 2131165215;
			
			// aapt resource value: 0x7f070026
			public const int type = 2131165222;
			
			// aapt resource value: 0x7f070011
			public const int username = 2131165201;
			
			// aapt resource value: 0x7f07002a
			public const int usernameEdit = 2131165226;
			
			// aapt resource value: 0x7f070028
			public const int workingTime = 2131165224;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddRestaurant = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Register = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Restaurants = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RestaurantView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SignMenu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int UserEdit = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu_main = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int account = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int add = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int exit = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int restaurants = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyActionBar = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
