//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 5.0.61118.0
// 
namespace DataAccess.RestaurantWebService
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BaseEntity", Namespace = "http://schemas.datacontract.org/2004/07/DataAccess.Entity")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DataAccess.RestaurantWebService.RestaurantEntity))]
    public partial class BaseEntity : object
    {

        private int IdField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "RestaurantEntity", Namespace = "http://schemas.datacontract.org/2004/07/DataAccess.Entity")]
    public partial class RestaurantEntity : DataAccess.RestaurantWebService.BaseEntity
    {

        private string AddressField;

        private System.DateTime CreateTimeField;

        private string DescriptionField;

        private string EmailField;

        private string ImageUrlField;

        private string NameField;

        private string PhoneField;

        private bool RestaurantsStatusField;

        private string TypeField;

        private string WorkingTimeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime
        {
            get
            {
                return this.CreateTimeField;
            }
            set
            {
                this.CreateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl
        {
            get
            {
                return this.ImageUrlField;
            }
            set
            {
                this.ImageUrlField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RestaurantsStatus
        {
            get
            {
                return this.RestaurantsStatusField;
            }
            set
            {
                this.RestaurantsStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkingTime
        {
            get
            {
                return this.WorkingTimeField;
            }
            set
            {
                this.WorkingTimeField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IRestaurantWebService")]
    public interface IRestaurantWebService
    {

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IRestaurantWebService/GetById", ReplyAction = "http://tempuri.org/IRestaurantWebService/GetByIdResponse")]
        System.IAsyncResult BeginGetById(int id, System.AsyncCallback callback, object asyncState);

        DataAccess.RestaurantWebService.RestaurantEntity EndGetById(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IRestaurantWebService/GetAll", ReplyAction = "http://tempuri.org/IRestaurantWebService/GetAllResponse")]
        System.IAsyncResult BeginGetAll(System.AsyncCallback callback, object asyncState);

        DataAccess.RestaurantWebService.RestaurantEntity[] EndGetAll(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IRestaurantWebService/Count", ReplyAction = "http://tempuri.org/IRestaurantWebService/CountResponse")]
        System.IAsyncResult BeginCount(System.AsyncCallback callback, object asyncState);

        int EndCount(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IRestaurantWebService/Save", ReplyAction = "http://tempuri.org/IRestaurantWebService/SaveResponse")]
        System.IAsyncResult BeginSave(DataAccess.RestaurantWebService.RestaurantEntity entity, System.AsyncCallback callback, object asyncState);

        void EndSave(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IRestaurantWebService/Delete", ReplyAction = "http://tempuri.org/IRestaurantWebService/DeleteResponse")]
        System.IAsyncResult BeginDelete(DataAccess.RestaurantWebService.RestaurantEntity entity, System.AsyncCallback callback, object asyncState);

        void EndDelete(System.IAsyncResult result);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestaurantWebServiceChannel : IRestaurantWebService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public GetByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public DataAccess.RestaurantWebService.RestaurantEntity Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((DataAccess.RestaurantWebService.RestaurantEntity)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public GetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public DataAccess.RestaurantWebService.RestaurantEntity[] Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((DataAccess.RestaurantWebService.RestaurantEntity[])(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public CountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public int Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestaurantWebServiceClient : System.ServiceModel.ClientBase<IRestaurantWebService>, IRestaurantWebService
    {

        private BeginOperationDelegate onBeginGetByIdDelegate;

        private EndOperationDelegate onEndGetByIdDelegate;

        private System.Threading.SendOrPostCallback onGetByIdCompletedDelegate;

        private BeginOperationDelegate onBeginGetAllDelegate;

        private EndOperationDelegate onEndGetAllDelegate;

        private System.Threading.SendOrPostCallback onGetAllCompletedDelegate;

        private BeginOperationDelegate onBeginCountDelegate;

        private EndOperationDelegate onEndCountDelegate;

        private System.Threading.SendOrPostCallback onCountCompletedDelegate;

        private BeginOperationDelegate onBeginSaveDelegate;

        private EndOperationDelegate onEndSaveDelegate;

        private System.Threading.SendOrPostCallback onSaveCompletedDelegate;

        private BeginOperationDelegate onBeginDeleteDelegate;

        private EndOperationDelegate onEndDeleteDelegate;

        private System.Threading.SendOrPostCallback onDeleteCompletedDelegate;

        private BeginOperationDelegate onBeginOpenDelegate;

        private EndOperationDelegate onEndOpenDelegate;

        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;

        private BeginOperationDelegate onBeginCloseDelegate;

        private EndOperationDelegate onEndCloseDelegate;

        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;

        public RestaurantWebServiceClient()
        {
        }

        public RestaurantWebServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public RestaurantWebServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public RestaurantWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public RestaurantWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Net.CookieContainer CookieContainer
        {
            get
            {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null))
                {
                    return httpCookieContainerManager.CookieContainer;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null))
                {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else
                {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }

        public event System.EventHandler<GetByIdCompletedEventArgs> GetByIdCompleted;

        public event System.EventHandler<GetAllCompletedEventArgs> GetAllCompleted;

        public event System.EventHandler<CountCompletedEventArgs> CountCompleted;

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SaveCompleted;

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteCompleted;

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IRestaurantWebService.BeginGetById(int id, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetById(id, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccess.RestaurantWebService.RestaurantEntity IRestaurantWebService.EndGetById(System.IAsyncResult result)
        {
            return base.Channel.EndGetById(result);
        }

        private System.IAsyncResult OnBeginGetById(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            int id = ((int)(inValues[0]));
            return ((IRestaurantWebService)(this)).BeginGetById(id, callback, asyncState);
        }

        private object[] OnEndGetById(System.IAsyncResult result)
        {
            DataAccess.RestaurantWebService.RestaurantEntity retVal = ((IRestaurantWebService)(this)).EndGetById(result);
            return new object[] {
                retVal};
        }

        private void OnGetByIdCompleted(object state)
        {
            if ((this.GetByIdCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetByIdCompleted(this, new GetByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void GetByIdAsync(int id)
        {
            this.GetByIdAsync(id, null);
        }

        public void GetByIdAsync(int id, object userState)
        {
            if ((this.onBeginGetByIdDelegate == null))
            {
                this.onBeginGetByIdDelegate = new BeginOperationDelegate(this.OnBeginGetById);
            }
            if ((this.onEndGetByIdDelegate == null))
            {
                this.onEndGetByIdDelegate = new EndOperationDelegate(this.OnEndGetById);
            }
            if ((this.onGetByIdCompletedDelegate == null))
            {
                this.onGetByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetByIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetByIdDelegate, new object[] {
                    id}, this.onEndGetByIdDelegate, this.onGetByIdCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IRestaurantWebService.BeginGetAll(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetAll(callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccess.RestaurantWebService.RestaurantEntity[] IRestaurantWebService.EndGetAll(System.IAsyncResult result)
        {
            return base.Channel.EndGetAll(result);
        }

        private System.IAsyncResult OnBeginGetAll(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((IRestaurantWebService)(this)).BeginGetAll(callback, asyncState);
        }

        private object[] OnEndGetAll(System.IAsyncResult result)
        {
            DataAccess.RestaurantWebService.RestaurantEntity[] retVal = ((IRestaurantWebService)(this)).EndGetAll(result);
            return new object[] {
                retVal};
        }

        private void OnGetAllCompleted(object state)
        {
            if ((this.GetAllCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllCompleted(this, new GetAllCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void GetAllAsync()
        {
            this.GetAllAsync(null);
        }

        public void GetAllAsync(object userState)
        {
            if ((this.onBeginGetAllDelegate == null))
            {
                this.onBeginGetAllDelegate = new BeginOperationDelegate(this.OnBeginGetAll);
            }
            if ((this.onEndGetAllDelegate == null))
            {
                this.onEndGetAllDelegate = new EndOperationDelegate(this.OnEndGetAll);
            }
            if ((this.onGetAllCompletedDelegate == null))
            {
                this.onGetAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllDelegate, null, this.onEndGetAllDelegate, this.onGetAllCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IRestaurantWebService.BeginCount(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginCount(callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int IRestaurantWebService.EndCount(System.IAsyncResult result)
        {
            return base.Channel.EndCount(result);
        }

        private System.IAsyncResult OnBeginCount(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((IRestaurantWebService)(this)).BeginCount(callback, asyncState);
        }

        private object[] OnEndCount(System.IAsyncResult result)
        {
            int retVal = ((IRestaurantWebService)(this)).EndCount(result);
            return new object[] {
                retVal};
        }

        private void OnCountCompleted(object state)
        {
            if ((this.CountCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CountCompleted(this, new CountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void CountAsync()
        {
            this.CountAsync(null);
        }

        public void CountAsync(object userState)
        {
            if ((this.onBeginCountDelegate == null))
            {
                this.onBeginCountDelegate = new BeginOperationDelegate(this.OnBeginCount);
            }
            if ((this.onEndCountDelegate == null))
            {
                this.onEndCountDelegate = new EndOperationDelegate(this.OnEndCount);
            }
            if ((this.onCountCompletedDelegate == null))
            {
                this.onCountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCountCompleted);
            }
            base.InvokeAsync(this.onBeginCountDelegate, null, this.onEndCountDelegate, this.onCountCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IRestaurantWebService.BeginSave(DataAccess.RestaurantWebService.RestaurantEntity entity, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSave(entity, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void IRestaurantWebService.EndSave(System.IAsyncResult result)
        {
            base.Channel.EndSave(result);
        }

        private System.IAsyncResult OnBeginSave(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            DataAccess.RestaurantWebService.RestaurantEntity entity = ((DataAccess.RestaurantWebService.RestaurantEntity)(inValues[0]));
            return ((IRestaurantWebService)(this)).BeginSave(entity, callback, asyncState);
        }

        private object[] OnEndSave(System.IAsyncResult result)
        {
            ((IRestaurantWebService)(this)).EndSave(result);
            return null;
        }

        private void OnSaveCompleted(object state)
        {
            if ((this.SaveCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }

        public void SaveAsync(DataAccess.RestaurantWebService.RestaurantEntity entity)
        {
            this.SaveAsync(entity, null);
        }

        public void SaveAsync(DataAccess.RestaurantWebService.RestaurantEntity entity, object userState)
        {
            if ((this.onBeginSaveDelegate == null))
            {
                this.onBeginSaveDelegate = new BeginOperationDelegate(this.OnBeginSave);
            }
            if ((this.onEndSaveDelegate == null))
            {
                this.onEndSaveDelegate = new EndOperationDelegate(this.OnEndSave);
            }
            if ((this.onSaveCompletedDelegate == null))
            {
                this.onSaveCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveCompleted);
            }
            base.InvokeAsync(this.onBeginSaveDelegate, new object[] {
                    entity}, this.onEndSaveDelegate, this.onSaveCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IRestaurantWebService.BeginDelete(DataAccess.RestaurantWebService.RestaurantEntity entity, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginDelete(entity, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void IRestaurantWebService.EndDelete(System.IAsyncResult result)
        {
            base.Channel.EndDelete(result);
        }

        private System.IAsyncResult OnBeginDelete(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            DataAccess.RestaurantWebService.RestaurantEntity entity = ((DataAccess.RestaurantWebService.RestaurantEntity)(inValues[0]));
            return ((IRestaurantWebService)(this)).BeginDelete(entity, callback, asyncState);
        }

        private object[] OnEndDelete(System.IAsyncResult result)
        {
            ((IRestaurantWebService)(this)).EndDelete(result);
            return null;
        }

        private void OnDeleteCompleted(object state)
        {
            if ((this.DeleteCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }

        public void DeleteAsync(DataAccess.RestaurantWebService.RestaurantEntity entity)
        {
            this.DeleteAsync(entity, null);
        }

        public void DeleteAsync(DataAccess.RestaurantWebService.RestaurantEntity entity, object userState)
        {
            if ((this.onBeginDeleteDelegate == null))
            {
                this.onBeginDeleteDelegate = new BeginOperationDelegate(this.OnBeginDelete);
            }
            if ((this.onEndDeleteDelegate == null))
            {
                this.onEndDeleteDelegate = new EndOperationDelegate(this.OnEndDelete);
            }
            if ((this.onDeleteCompletedDelegate == null))
            {
                this.onDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteDelegate, new object[] {
                    entity}, this.onEndDeleteDelegate, this.onDeleteCompletedDelegate, userState);
        }

        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }

        private object[] OnEndOpen(System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }

        private void OnOpenCompleted(object state)
        {
            if ((this.OpenCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }

        public void OpenAsync()
        {
            this.OpenAsync(null);
        }

        public void OpenAsync(object userState)
        {
            if ((this.onBeginOpenDelegate == null))
            {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null))
            {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null))
            {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }

        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }

        private object[] OnEndClose(System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }

        private void OnCloseCompleted(object state)
        {
            if ((this.CloseCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }

        public void CloseAsync()
        {
            this.CloseAsync(null);
        }

        public void CloseAsync(object userState)
        {
            if ((this.onBeginCloseDelegate == null))
            {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null))
            {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null))
            {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }

        protected override IRestaurantWebService CreateChannel()
        {
            return new RestaurantWebServiceClientChannel(this);
        }

        private class RestaurantWebServiceClientChannel : ChannelBase<IRestaurantWebService>, IRestaurantWebService
        {

            public RestaurantWebServiceClientChannel(System.ServiceModel.ClientBase<IRestaurantWebService> client) :
                    base(client)
            {
            }

            public System.IAsyncResult BeginGetById(int id, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("GetById", _args, callback, asyncState);
                return _result;
            }

            public DataAccess.RestaurantWebService.RestaurantEntity EndGetById(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                DataAccess.RestaurantWebService.RestaurantEntity _result = ((DataAccess.RestaurantWebService.RestaurantEntity)(base.EndInvoke("GetById", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginGetAll(System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAll", _args, callback, asyncState);
                return _result;
            }

            public DataAccess.RestaurantWebService.RestaurantEntity[] EndGetAll(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                DataAccess.RestaurantWebService.RestaurantEntity[] _result = ((DataAccess.RestaurantWebService.RestaurantEntity[])(base.EndInvoke("GetAll", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginCount(System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Count", _args, callback, asyncState);
                return _result;
            }

            public int EndCount(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("Count", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginSave(DataAccess.RestaurantWebService.RestaurantEntity entity, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = entity;
                System.IAsyncResult _result = base.BeginInvoke("Save", _args, callback, asyncState);
                return _result;
            }

            public void EndSave(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                base.EndInvoke("Save", _args, result);
            }

            public System.IAsyncResult BeginDelete(DataAccess.RestaurantWebService.RestaurantEntity entity, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = entity;
                System.IAsyncResult _result = base.BeginInvoke("Delete", _args, callback, asyncState);
                return _result;
            }

            public void EndDelete(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                base.EndInvoke("Delete", _args, result);
            }
        }
    }
}